# Generated by Django 3.0.2 on 2020-01-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Puzzle category (ie. Rebus)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the puzzles title', max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('puzzle_text', models.CharField(help_text='Enter the puzzle text here', max_length=1000)),
                ('puzzle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='puzzlehunt.PuzzleType')),
            ],
        ),
    ]
