# Generated by Django 3.0.2 on 2020-01-29 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0002_auto_20200128_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, help_text='A name for the document', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.CharField(blank=True, help_text='Optional description for the document.', max_length=255),
        ),
    ]
