# Generated by Django 3.0.2 on 2020-01-29 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzlehunt', '0003_auto_20200129_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(default=False, help_text='The answer for the puzzle.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puzzle',
            name='case_sensitive',
            field=models.BooleanField(default=False),
        ),
    ]
