# Generated by Django 3.0.2 on 2020-02-02 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Document type (ie. jpg, png)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleDifficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PuzzleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Puzzle category (ie. Rebus)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Enter the puzzle's title", max_length=200)),
                ('created', models.DateTimeField(verbose_name='date created')),
                ('puzzle_text', models.CharField(help_text='Enter the puzzle text here', max_length=1000)),
                ('answer', models.CharField(help_text='The answer for the puzzle.', max_length=1000)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('difficulty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticweb.PuzzleDifficulty')),
                ('puzzle_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticweb.PuzzleType')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A name for the document', max_length=200)),
                ('document', models.FileField(upload_to='document_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Optional description for the document.', max_length=255)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staticweb.DocumentType')),
            ],
        ),
    ]
